# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-26 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20161221_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='attachment', verbose_name='Attachment')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, default='', help_text='This is a help text', verbose_name='My video'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='images',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post', verbose_name='Images'),
        ),
    ]
