# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-26 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20161226_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='attachment', verbose_name='Attachment'),
        ),
    ]
