# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-26 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20161226_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='images',
        ),
        migrations.AddField(
            model_name='attachment',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Post', verbose_name='Post'),
        ),
    ]
