# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-26 21:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20161226_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='message',
            new_name='post',
        ),
    ]
